# Real-Data RAG + MDE Schema Evolution Experiment

**Purpose:** run the project's real schema-matching and schema-evolution pipeline without the controlled mock benchmark.

Pipeline:

`U-Schema → PostgreSQL introspection → real RAG/FAISS → SemanticDecisionService → MDEValidator → DecisionPolicy → EvolutionPlanner → MigrationBuilder`

This notebook is deliberately **dry-run by default**: SQL is generated and inspected but not executed against the database.

## 0. Experimental principles

- The retrieval boundary uses the existing `RAGSchemaMatcher`.
- The target schema is obtained from the configured PostgreSQL database.
- The knowledge base is built from the introspected target schema.
- No `benchmark.jsonl` candidates or canned scores are used for the real run.
- The notebook attempts to reuse the project's existing services instead of reimplementing them.
- If the exact constructor/interface of `SemanticDecisionService` differs from the adapter below, the adapter cell reports the mismatch instead of fabricating results.

In [ ]:
from pathlib import Path
import os
import sys
import json
import logging
import importlib.util
from typing import Any, Dict, List, Optional

import pandas as pd

# Locate repository root robustly when the notebook is placed in the repository.
CANDIDATES = [
    Path.cwd(),
    Path.cwd().parent,
]
REPO_ROOT = next(
    (p for p in CANDIDATES if (p / "src").exists()),
    Path.cwd()
)
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

print("Repository:", REPO_ROOT)

Repository: d:\memoire\rag\1.0.0

## 1. Configuration

Change only the paths/provider settings in this cell before running the experiment.

In [ ]:
# ---- Files ----
USCHEMA_FILE = REPO_ROOT / "scripts" / "uschema.json"
KB_FILE = REPO_ROOT / "data" / "rag" / "knowledge_base_enriched.jsonl"
ARTIFACT_DIR = REPO_ROOT / "artifacts" / "notebook_real_experiment"

# ---- Database ----
DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql://test:test@localhost:55432/test"
)
DIALECT = "postgresql"

# ---- RAG ----
INDEX_TYPE = "Flat"          # safest for small/medium experimental schemas
TOP_K = 5
TABLE_THRESHOLD = 0.35
COLUMN_THRESHOLD = 0.35

# ---- Decision layer ----
TAU_MATCH = 0.85
TAU_REVIEW = 0.70

# ---- Safety ----
EXECUTE_SQL = False

ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)

print("U-Schema:", USCHEMA_FILE)
print("KB:", KB_FILE)
print("Database:", DATABASE_URL.split("@")[-1])
print("Execute SQL:", EXECUTE_SQL)

U-Schema: d:\memoire\rag\1.0.0\scripts\uschema.json
KB: d:\memoire\rag\1.0.0\data\rag\knowledge_base_enriched.jsonl
Database: localhost:55432/test
Execute SQL: False

## 2. Dependency and environment check

In [ ]:
packages = [
    "pandas",
    "numpy",
    "faiss",
    "sqlalchemy",
    "psycopg2",
]

status = []
for package in packages:
    status.append({
        "package": package,
        "available": importlib.util.find_spec(package) is not None
    })

env_df = pd.DataFrame(status)
display(env_df)

missing = env_df.loc[~env_df["available"], "package"].tolist()
if missing:
    print("Missing packages:", missing)
    print("Install them in the project's environment before continuing.")
else:
    print("Core runtime dependencies are available.")

      package  available
0      pandas       True
1       numpy       True
2       faiss       True
3  sqlalchemy       True
4    psycopg2       True

Core runtime dependencies are available.

In [ ]:
# %pip install psycopg2

## 3. Import the existing project services

In [ ]:
from src.infrastructure.di_container import DIContainer

from src.domain.entities.schema import (
    USchema,
    USchemaEntity,
    USchemaAttribute,
    DataType,
    SchemaMetadata,
)
from src.domain.entities.rules import NamingConvention
from src.domain.entities.evolution import ChangeType
from src.domain.entities.experimental import (
    DecisionType,
    SemanticDecision,
    MDEStatus,
)

from src.domain.services.diff_engine import DiffEngine
from src.domain.services.migration_builder import MigrationBuilder
from src.domain.services.decision_policy import DecisionPolicy, DecisionThresholds
from src.domain.services.evolution_planner import EvolutionPlanner
from src.domain.services.mde_validator import MDEValidator, StructuralContext
from src.domain.services.relevance_policy import RelevancePolicy

from src.infrastructure.rag.embedding_service import (
    EmbeddingService,
    LocalEmbeddingProvider,
)
from src.infrastructure.rag.vector_store import RAGVectorStore
from src.infrastructure.rag.rag_schema_matcher import RAGSchemaMatcher
from src.infrastructure.rag.semantic_decision_service import SemanticDecisionService

print("Project imports loaded.")

c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Project imports loaded.

## 4. Load and normalize the real U-Schema

In [ ]:
STR2DT = {
    "string": DataType.STRING,
    "integer": DataType.INTEGER,
    "int": DataType.INTEGER,
    "decimal": DataType.DECIMAL,
    "float": DataType.DECIMAL,
    "boolean": DataType.BOOLEAN,
    "bool": DataType.BOOLEAN,
    "timestamp": DataType.TIMESTAMP,
    "datetime": DataType.TIMESTAMP,
    "date": DataType.DATE,
    "json": DataType.JSON,
    "uuid": DataType.UUID,
}

def _to_datatype(value):
    if isinstance(value, DataType):
        return value
    return STR2DT.get(str(value).strip().lower(), DataType.STRING)

def load_uschema(uschema_json: Dict[str, Any]) -> USchema:
    entities = []

    root = uschema_json.get("uSchemaModel", {})
    for entity_block in root.get("entities", []):
        et = entity_block.get("EntityType", {})
        entity_name = et.get("name", "").strip().lower()
        attributes = []

        for variation in et.get("variations", []):
            sv = variation.get("StructuralVariation", {})

            for prop_block in sv.get("properties", []):
                attr_list = prop_block.get("Attribute") or []
                if isinstance(attr_list, dict):
                    attr_list = [attr_list]

                for attr in attr_list:
                    name = attr.get("name", "").strip().lower()
                    if not name:
                        continue
                    attributes.append(
                        USchemaAttribute(
                            name=name,
                            data_type=_to_datatype(attr.get("type", "string")),
                            is_key=bool(attr.get("iskey", False)),
                        )
                    )

            for agg_block in sv.get("aggregates", []):
                agg = agg_block.get("Aggregation")
                if agg:
                    attributes.append(
                        USchemaAttribute(
                            name=f"{agg.get('name','').lower()}->{agg.get('target','').lower()}",
                            data_type=DataType.JSON,
                            is_key=False,
                        )
                    )

            for ref_block in sv.get("references", []):
                ref = ref_block.get("Reference")
                if ref:
                    attributes.append(
                        USchemaAttribute(
                            name=f"{ref.get('name','').lower()}->{ref.get('target','').lower()}",
                            data_type=DataType.JSON,
                            is_key=False,
                        )
                    )

        if entity_name:
            entities.append(
                USchemaEntity(name=entity_name, attributes=attributes)
            )

    return USchema(entities=entities)

if not USCHEMA_FILE.exists():
    raise FileNotFoundError(
        f"U-Schema file not found: {USCHEMA_FILE}. "
        "Set USCHEMA_FILE to the real project file."
    )

with open(USCHEMA_FILE, "r", encoding="utf-8") as f:
    uschema_json = json.load(f)

uschema = load_uschema(uschema_json)

uschema_rows = []
for entity in uschema.entities:
    for attr in entity.attributes:
        uschema_rows.append({
            "entity": entity.name,
            "attribute": attr.name,
            "data_type": getattr(attr.data_type, "value", str(attr.data_type)),
            "is_key": getattr(attr, "is_key", False),
        })

uschema_df = pd.DataFrame(uschema_rows)
print(f"Entities: {len(uschema.entities)}")
print(f"Attributes: {len(uschema_rows)}")
display(uschema_df.head(30))

Entities: 8
Attributes: 32

          entity                     attribute data_type  is_key
0        patient                    patient_id    string    True
1        patient                          name    string   False
2        patient                        gender    string   False
3        patient                           dob    string   False
4        patient                      deceased    string   False
5        patient                     allergies    string   False
6        patient                     caregiver    string   False
7     caregivers                          cgid    string    True
8     caregivers                         label    string   False
9     caregivers                   description    string   False
10       contact                         phone    string   False
11       contact              address->address      json   False
12       address                         line1    string   False
13       address                          city    string   False
14       address                       country    string   False
15     admission                  admission_id    string   False
16     admission                admission_type    string   False
17     admission                    admit_time    string   False
18     admission                discharge_time    string   False
19     admission             telemedicine_flag   boolean   False
20     admission                    visit_mode    string   False
21     admission   prescriptions->prescription      json   False
22     admission              imaging->imaging      json   False
23  prescription                          drug    string   False
24  prescription                          dose    string   False
25  prescription                         route    string   False
26  prescription                     frequency    string   False
27       imaging                      modality    string   False
28       imaging                     body_site    string   False
29       imaging  ai_annotations->aiannotation      json   False

## 5. Introspect the real PostgreSQL target schema

In [ ]:
DATABASE_URL = "postgresql://odoo:odoo@localhost:5432/mimic"
container = DIContainer()
container.configure(DATABASE_URL, DIALECT)

inspector = container.get_inspector()
current_schema: SchemaMetadata = inspector.introspect_schema()

print(f"Target tables detected: {len(current_schema.tables)}")
print("Schema introspection completed.")

Target tables detected: 72
Schema introspection completed.

In [ ]:
def schema_to_dataframe(schema):
    rows = []
    for table in schema.tables:
        table_name = getattr(table, "name", None) or getattr(table, "table_name", None)
        columns = getattr(table, "columns", []) or []
        for column in columns:
            rows.append({
                "table": table_name,
                "column": getattr(column, "name", None),
                "data_type": str(getattr(column, "data_type", "")),
                "nullable": getattr(column, "nullable", None),
                "is_primary_key": getattr(column, "is_primary_key", None),
                "is_foreign_key": getattr(column, "is_foreign_key", None),
            })
    return pd.DataFrame(rows)

schema_df = schema_to_dataframe(current_schema)
display(schema_df.head(50))

,table,column,data_type,nullable,is_primary_key,is_foreign_key
0,admissions,row_id,integer,False,None,None
1,admissions,subject_id,integer,False,None,None
2,admissions,hadm_id,integer,True,None,None
3,admissions,admittime,timestamp without time zone,True,None,None
4,admissions,dischtime,timestamp without time zone,True,None,None
5,admissions,deathtime,timestamp without time zone,True,None,None
6,admissions,admission_type,character varying(50),True,None,None
7,admissions,admission_location,character varying(50),True,None,None
8,admissions,discharge_location,character varying(50),True,None,None
9,admissions,insurance,character varying(255),True,None,None
10,admissions,language,character varying(10),True,None,None
11,admissions,religion,character varying(50),True,None,None
12,admissions,marital_status,character varying(50),True,None,None
13,admissions,ethnicity,character varying(200),True,None,None
14,admissions,edregtime,timestamp without time zone,True,None,None
15,admissions,edouttime,timestamp without time zone,True,None,None
16,admissions,diagnosis,character varying(255),True,None,None
17,admissions,hospital_expire_flag,smallint,True,None,None
18,admissions,has_chartevents_data,smallint,True,None,None
19,admissions,id,integer,True,None,None
20,admissions,admit_time,text,True,None,None
21,admissions,patientsid,integer,True,None,None
22,admissions,telemedicine_flag,integer,True,None,None
23,admissions,visit_mode,text,True,None,None
24,admissions_items,id,bigint,False,None,None
25,admissions_items,hadm_id,bigint,True,None,None
26,admissions_items,admittime,text,True,None,None
27,admissions_items,dischtime,text,True,None,None
28,admissions_items,deathtime,text,True,None,None
29,admissions_items,admission_type,text,True,None,None
30,admissions_items,valid_from,timestamp with time zone,False,None,None
31,admissions_items,valid_to,timestamp with time zone,True,None,None
32,admissions_items,hadm_id_v1,bigint,True,None,None
33,admissions_items,admittime_v1,text,True,None,None
34,admissions_items,dischtime_v1,text,True,None,None
35,admissions_items,deathtime_v1,text,True,None,None
36,admissions_items,admission_type_v1,text,True,None,None
37,attachments,id,integer,False,None,None
38,attachments,attachments,text,True,None,None
39,attachments,online_consultationsid,integer,True,None,None
40,callout,row_id,integer,False,None,None
41,callout,subject_id,integer,False,None,None
42,callout,hadm_id,integer,False,None,None
43,callout,submit_wardid,integer,True,None,None
44,callout,submit_careunit,character varying(15),True,None,None
45,callout,curr_wardid,integer,True,None,None
46,callout,curr_careunit,character varying(15),True,None,None
47,callout,callout_wardid,integer,True,None,None
48,callout,callout_service,character varying(10),False,None,None
49,callout,request_tele,smallint,False,None,None

## 6. Build the real RAG matcher and FAISS index

In [ ]:
from src.infrastructure.llm.llm_client import BaseLLMClient


def build_matcher(index_type, table_threshold, column_threshold, top_k):
    provider = LocalEmbeddingProvider()
    embedding_service = EmbeddingService(provider)
    vector_store = RAGVectorStore(
        dimension=provider.dimension,
        index_type=index_type,
    )

    # Keep the project's current LLM client construction in one place.
    # The matcher itself remains the production project implementation.
    from src.infrastructure.llm.factory import LLMFactory

    llm_client = BaseLLMClient(model="phi3:mini", temperature=0.1) 

    return RAGSchemaMatcher(
        embedding_service=embedding_service,
        vector_store=vector_store,
        llm_client=llm_client,
        table_accept_threshold=table_threshold,
        column_accept_threshold=column_threshold,
        top_k_search=top_k,
    )

matcher = build_matcher(
    INDEX_TYPE,
    TABLE_THRESHOLD,
    COLUMN_THRESHOLD,
    TOP_K,
)

def build_kb_and_index(matcher, schema, kb_file=None):
    kb_docs = matcher.build_kb(schema)

    if kb_file and Path(kb_file).exists():
        with open(kb_file, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                doc = json.loads(line)
                content = doc.get("content")
                if content:
                    kb_docs.append(content)

    matcher.index_kb(kb_docs)
    return kb_docs

kb_docs = build_kb_and_index(
    matcher,
    current_schema,
    str(KB_FILE) if KB_FILE.exists() else None,
)

print(f"Indexed KB documents: {len(kb_docs)}")

ModuleNotFoundError: No module named 'src'

## 7. Real RAG entity → table matching

In [ ]:
table_rows = []

for entity in uschema.entities:
    attr_names = [a.name for a in entity.attributes]

    result = matcher.match_table(
        entity.name,
        attr_names,
    )

    table_rows.append({
        "source_entity": entity.name,
        "target_table": result.target_name,
        "confidence": result.confidence,
        "rationale": result.rationale,
    })

table_df = pd.DataFrame(table_rows)
display(table_df)

```json
{
    "match": "patients",
    "confidence": 0.95,
    "why": "The 'patients' table contains patient_id (integer), name (text), gender (typically text or categorical data type for sex/gender representation in MIMIC-III), dob (timestamp representing date of birth). The attributes align with the conceptual entity and datatypes are compatible. This is a primary table that represents individual patients, which fits our patient business object."
}
```
```json
{
    "match": "caregivers",
    "confidence": 0.95,
    "why": "The 'cgid' column in table MIMIC_CareGiver corresponds to a unique identifier for caregivers and fits the concept of an entity ID; label is analogous to name which matches with description attribute."
}
```

## 8. Real RAG attribute → column matching

In [ ]:
def datatype_to_sql(data_type):
    value = getattr(data_type, "value", str(data_type)).upper()

    if "INTEGER" in value or value == "INT":
        return "INTEGER"
    if "DECIMAL" in value or "FLOAT" in value:
        return "DECIMAL(10,2)"
    if "TIMESTAMP" in value or "DATETIME" in value:
        return "TIMESTAMP"
    if value == "DATE":
        return "DATE"
    if "BOOLEAN" in value or value == "BOOL":
        return "BOOLEAN"
    if "UUID" in value:
        return "UUID"
    return "VARCHAR(255)"

attribute_rows = []

for entity in uschema.entities:
    table_result = matcher.match_table(
        entity.name,
        [a.name for a in entity.attributes],
    )

    for attr in entity.attributes:
        if table_result.target_name:
            column_result = matcher.match_column(
                table_result.target_name,
                attr.name,
                datatype_to_sql(attr.data_type),
            )

            attribute_rows.append({
                "source_entity": entity.name,
                "source_attribute": attr.name,
                "source_type": getattr(attr.data_type, "value", str(attr.data_type)),
                "target_table": table_result.target_name,
                "target_column": column_result.target_name,
                "confidence": column_result.confidence,
                "rationale": column_result.rationale,
            })
        else:
            attribute_rows.append({
                "source_entity": entity.name,
                "source_attribute": attr.name,
                "source_type": getattr(attr.data_type, "value", str(attr.data_type)),
                "target_table": None,
                "target_column": None,
                "confidence": 0.0,
                "rationale": "No table match",
            })

attribute_df = pd.DataFrame(attribute_rows)
display(attribute_df)

,source_entity,source_attribute,source_type,target_table,target_column,confidence,rationale
0,patient,patient_id,string,NaN,NaN,0.00,No table match
1,patient,name,string,NaN,NaN,0.00,No table match
2,patient,gender,string,NaN,NaN,0.00,No table match
3,patient,dob,string,NaN,NaN,0.00,No table match
4,patient,deceased,string,NaN,NaN,0.00,No table match
5,patient,allergies,string,NaN,NaN,0.00,No table match
6,patient,caregiver,string,NaN,NaN,0.00,No table match
7,caregivers,cgid,string,CAREGIVERS,NaN,0.00,No column candidates found in table CAREGIVERS
8,caregivers,label,string,CAREGIVERS,NaN,0.00,No column candidates found in table CAREGIVERS
9,caregivers,description,string,CAREGIVERS,NaN,0.00,No column candidates found in table CAREGIVERS
10,contact,phone,string,NaN,NaN,0.00,No table match
11,contact,address->address,json,NaN,NaN,0.00,No table match
12,address,line1,string,NaN,NaN,0.00,No table match
13,address,city,string,NaN,NaN,0.00,No table match
14,address,country,string,NaN,NaN,0.00,No table match
15,admission,admission_id,string,ADMISSIONS,NaN,0.00,No column candidates found in table ADMISSIONS
16,admission,admission_type,string,ADMISSIONS,NaN,0.00,No column candidates found in table ADMISSIONS
17,admission,admit_time,string,ADMISSIONS,NaN,0.00,No column candidates found in table ADMISSIONS
18,admission,discharge_time,string,ADMISSIONS,NaN,0.00,No column candidates found in table ADMISSIONS
19,admission,telemedicine_flag,boolean,ADMISSIONS,NaN,0.00,No column candidates found in table ADMISSIONS
20,admission,visit_mode,string,ADMISSIONS,NaN,0.00,No column candidates found in table ADMISSIONS
21,admission,prescriptions->prescription,json,ADMISSIONS,NaN,0.00,No column candidates found in table ADMISSIONS
22,admission,imaging->imaging,json,ADMISSIONS,NaN,0.00,No column candidates found in table ADMISSIONS
23,prescription,drug,string,prescriptions,NaN,0.00,The candidate 'drug_type' represents the class...
24,prescription,dose,string,prescriptions,NaN,0.00,"None of the candidate columns (route, gsn) sem..."
25,prescription,route,string,prescriptions,prescriptions.route,0.98,Exact match in column name and high semantic a...
26,prescription,frequency,string,prescriptions,NaN,0.00,No column candidates found in table prescriptions
27,imaging,modality,string,NaN,NaN,0.00,No table match
28,imaging,body_site,string,NaN,NaN,0.00,No table match
29,imaging,ai_annotations->aiannotation,json,NaN,NaN,0.00,No table match
30,aiannotation,label,string,NaN,NaN,0.00,No table match
31,aiannotation,confidence,string,NaN,NaN,0.00,No table match

## 9. Adapter boundary for `SemanticDecisionService`

The project contains two interfaces:

1. `RAGSchemaMatcher`, which performs real table/column retrieval.
2. `SemanticDecisionService`, which consumes a retriever/LLM-orchestrator abstraction.

The notebook therefore uses a **thin adapter** rather than replacing either service.

If the installed project version has a different method signature, the cell raises a clear error so the interface can be aligned in the source code. It never inserts benchmark scores.

In [ ]:
from types import SimpleNamespace

class RealRAGRetrieverAdapter:
    """Adapter exposing real RAG candidates to SemanticDecisionService."""

    def __init__(self, matcher, top_k=5):
        self.matcher = matcher
        self.top_k = top_k

    def retrieve_candidates(self, query):
        # SemanticDecisionService expects (document, bi_score, cross_score).
        # We obtain candidates from the actual matcher.
        source_name = getattr(query, "path", None) or getattr(query, "name", None)
        if not source_name:
            raise ValueError("Source query has no path/name.")

        parts = str(source_name).split(".")
        if len(parts) >= 2:
            entity_name = parts[-2]
            attribute_name = parts[-1]
        else:
            entity_name = parts[0]
            attribute_name = parts[0]

        table_result = self.matcher.match_table(entity_name, [attribute_name])

        if not table_result.target_name:
            return []

        column_result = self.matcher.match_column(
            table_result.target_name,
            attribute_name,
            "VARCHAR(255)",
        )

        target = column_result.target_name
        if not target:
            return []

        # Build the minimal document shape expected by SemanticDecisionService.
        try:
            from src.domain.entities.rag_schema import KnowledgeBaseDocument
            doc = KnowledgeBaseDocument(
                id=f"{table_result.target_name}.{target}",
                table=table_result.target_name,
                column=target,
                content=f"{table_result.target_name}.{target}",
                metadata={},
            )
        except Exception as exc:
            raise RuntimeError(
                "Could not construct KnowledgeBaseDocument for the "
                "SemanticDecisionService adapter."
            ) from exc

        score = float(column_result.confidence or 0.0)
        return [(doc, score, score)]


class RealRAGLLMOrchestratorAdapter:
    """Adapter that delegates LLM matching to the project's RAG matcher.

    No canned benchmark output is used.
    """

    def __init__(self, matcher):
        self.matcher = matcher

    def match_field(self, query, docs, bi_scores, cross_scores):
        candidates = []

        for doc, bi, cross in zip(docs, bi_scores, cross_scores):
            target = f"{doc.table}.{doc.column}"
            score = float(max(bi, cross))

            candidates.append(
                SimpleNamespace(
                    target=target,
                    confidence_llm=score,
                    confidence_model=float(bi),
                    rationale="Score delegated from the real RAG matcher.",
                    guardrails=[],
                )
            )

        return SimpleNamespace(candidates=candidates)

real_retriever = RealRAGRetrieverAdapter(matcher, top_k=TOP_K)
real_llm = RealRAGLLMOrchestratorAdapter(matcher)

print("Real RAG adapters initialized.")

Real RAG adapters initialized.

## 10. Decision layer initialization

In [ ]:
scoring_system = __import__(
    "src.infrastructure.rag.scoring_system",
    fromlist=["HybridScoringSystem"]
).HybridScoringSystem()

mde_validator = MDEValidator()
relevance_policy = RelevancePolicy()

decision_policy = DecisionPolicy(
    thresholds=DecisionThresholds(
        tau_match=TAU_MATCH,
        tau_review=TAU_REVIEW,
    ),
    relevance_policy=relevance_policy,
)

evolution_planner = EvolutionPlanner()
migration_builder = MigrationBuilder(DIALECT)

print("Decision layer initialized.")

Decision layer initialized.

## 11. End-to-end SemanticDecision → MDE → Policy experiment

This section uses the real U-Schema attributes and real target schema metadata.

For each source attribute:

1. obtain real RAG evidence;
2. select the best semantic candidate;
3. validate type/structural compatibility;
4. apply the real decision policy;
5. create an evolution operation only when the policy returns `EVOLVE`.

In [ ]:
decision_rows = []
mde_rows = []
evolution_rows = []
schema_changes = []

def find_target_column_metadata(schema_df, table_name, column_name):
    if schema_df.empty or not table_name or not column_name:
        return {}
    hit = schema_df[
        (schema_df["table"].astype(str) == str(table_name)) &
        (schema_df["column"].astype(str) == str(column_name))
    ]
    if hit.empty:
        return {}
    return hit.iloc[0].to_dict()

# Use the actual RAG mapping table as the evidence source.
for row in attribute_rows:
    source_entity = row["source_entity"]
    source_attribute = row["source_attribute"]
    target_table = row["target_table"]
    target_column = row["target_column"]

    source_attr = next(
        (
            a for e in uschema.entities if e.name == source_entity
            for a in e.attributes if a.name == source_attribute
        ),
        None,
    )

    if source_attr is None:
        continue

    # If the RAG layer found no candidate, let the policy decide on missing evidence.
    semantic_decision = None

    if target_table and target_column:
        try:
            from src.domain.entities.rag_schema import SourceField

            source_field = SourceField(
                path=f"{source_entity}.{source_attribute}",
                name_tokens=[source_entity, source_attribute],
                inferred_type=datatype_to_sql(source_attr.data_type),
                hints=[],
            )

            # Preferred path: use the project's SemanticDecisionService.
            semantic_service = SemanticDecisionService(
                retriever=real_retriever,
                llm_orchestrator=real_llm,
                scoring_system=scoring_system,
                top_k=TOP_K,
            )

            semantic_decisions = semantic_service.evaluate_source_element(
                source_field
            )

            if semantic_decisions:
                semantic_decision = max(
                    semantic_decisions,
                    key=lambda x: x.combined_score,
                )

        except Exception as exc:
            # We do not fabricate a semantic decision.
            print(
                f"[WARNING] SemanticDecisionService failed for "
                f"{source_entity}.{source_attribute}: {exc}"
            )

    target_meta = find_target_column_metadata(
        schema_df,
        target_table,
        target_column,
    )

    mde_result = None

    if semantic_decision is not None:
        structural_context = StructuralContext(
            is_primary_key=bool(target_meta.get("is_primary_key", False)),
            is_foreign_key=bool(target_meta.get("is_foreign_key", False)),
            nullable=True if pd.isna(target_meta.get("nullable", True)) else bool(target_meta.get("nullable", True)),
            table_name=target_table,
            column_name=target_column,
        )

        try:
            mde_result = mde_validator.validate(
                source=source_attr,
                target_type=str(target_meta.get("data_type", "string")),
                structural_context=structural_context,
            )
        except Exception as exc:
            print(
                f"[WARNING] MDE validation failed for "
                f"{source_entity}.{source_attribute}: {exc}"
            )

    decision_result = decision_policy.decide(
        source_element=f"{source_entity}.{source_attribute}",
        semantic_decision=semantic_decision,
        mde_validation=mde_result,
        semantic_evidence_for_relevance=float(row.get("confidence", 0.0)),
    )

    semantic_score = (
        float(semantic_decision.combined_score)
        if semantic_decision is not None
        else float(row.get("confidence", 0.0))
    )

    decision_rows.append({
        "source_entity": source_entity,
        "source_attribute": source_attribute,
        "target_table": target_table,
        "target_column": target_column,
        "semantic_score": semantic_score,
        "mde_status": getattr(getattr(mde_result, "status", None), "value", None),
        "decision": decision_result.decision_type.value,
    })

    if mde_result is not None:
        mde_rows.append({
            "source_entity": source_entity,
            "source_attribute": source_attribute,
            "target_table": target_table,
            "target_column": target_column,
            "type_score": mde_result.type_score,
            "structural_score": mde_result.structural_score,
            "status": mde_result.status.value,
            "violations": mde_result.violations,
        })

    if decision_result.decision_type == DecisionType.EVOLVE:
        parent_table = source_entity

        try:
            change = evolution_planner.plan(
                decision=decision_result,
                source_attribute=source_attr,
                target_table=parent_table,
            )

            if change is not None:
                schema_changes.append(change)
                evolution_rows.append({
                    "source_entity": source_entity,
                    "source_attribute": source_attribute,
                    "change_type": change.change_type.value,
                    "target_table": change.target_table,
                    "target_column": change.target_column,
                    "data_type": change.data_type,
                })
        except Exception as exc:
            print(
                f"[WARNING] Evolution planning failed for "
                f"{source_entity}.{source_attribute}: {exc}"
            )

decision_df = pd.DataFrame(decision_rows)
mde_df = pd.DataFrame(mde_rows)
evolution_df = pd.DataFrame(evolution_rows)

display(decision_df)

[WARNING] SemanticDecisionService failed for prescription.route: 1 validation error for SourceField
inferred_type
  Input should be 'datetime', 'integer', 'float', 'text', 'boolean', 'code' or 'id' [type=enum, input_value='VARCHAR(255)', input_type=str]
    For further information visit https://errors.pydantic.dev/2.13/v/enum

,source_entity,source_attribute,target_table,target_column,semantic_score,mde_status,decision
0,patient,patient_id,NaN,NaN,0.00,None,REJECT
1,patient,name,NaN,NaN,0.00,None,REJECT
2,patient,gender,NaN,NaN,0.00,None,REJECT
3,patient,dob,NaN,NaN,0.00,None,REJECT
4,patient,deceased,NaN,NaN,0.00,None,REJECT
5,patient,allergies,NaN,NaN,0.00,None,REJECT
6,patient,caregiver,NaN,NaN,0.00,None,REJECT
7,caregivers,cgid,CAREGIVERS,NaN,0.00,None,REJECT
8,caregivers,label,CAREGIVERS,NaN,0.00,None,REJECT
9,caregivers,description,CAREGIVERS,NaN,0.00,None,REJECT
10,contact,phone,NaN,NaN,0.00,None,REJECT
11,contact,address->address,NaN,NaN,0.00,None,REJECT
12,address,line1,NaN,NaN,0.00,None,REJECT
13,address,city,NaN,NaN,0.00,None,REJECT
14,address,country,NaN,NaN,0.00,None,REJECT
15,admission,admission_id,ADMISSIONS,NaN,0.00,None,REJECT
16,admission,admission_type,ADMISSIONS,NaN,0.00,None,REJECT
17,admission,admit_time,ADMISSIONS,NaN,0.00,None,REJECT
18,admission,discharge_time,ADMISSIONS,NaN,0.00,None,REJECT
19,admission,telemedicine_flag,ADMISSIONS,NaN,0.00,None,REJECT
20,admission,visit_mode,ADMISSIONS,NaN,0.00,None,REJECT
21,admission,prescriptions->prescription,ADMISSIONS,NaN,0.00,None,REJECT
22,admission,imaging->imaging,ADMISSIONS,NaN,0.00,None,REJECT
23,prescription,drug,prescriptions,NaN,0.00,None,REJECT
24,prescription,dose,prescriptions,NaN,0.00,None,REJECT
25,prescription,route,prescriptions,prescriptions.route,0.98,None,EVOLVE
26,prescription,frequency,prescriptions,NaN,0.00,None,REJECT
27,imaging,modality,NaN,NaN,0.00,None,REJECT
28,imaging,body_site,NaN,NaN,0.00,None,REJECT
29,imaging,ai_annotations->aiannotation,NaN,NaN,0.00,None,REJECT
30,aiannotation,label,NaN,NaN,0.00,None,REJECT
31,aiannotation,confidence,NaN,NaN,0.00,None,REJECT

## 12. MDE validation results

In [ ]:
if mde_df.empty:
    print("No MDE validation records were produced.")
else:
    display(mde_df)

    print("\nMDE status counts:")
    display(
        mde_df["status"]
        .value_counts(dropna=False)
        .rename_axis("status")
        .reset_index(name="count")
    )

No MDE validation records were produced.

## 13. Final decisions

In [ ]:
if decision_df.empty:
    print("No final decisions were produced.")
else:
    display(decision_df)

    print("\nDecision counts:")
    display(
        decision_df["decision"]
        .value_counts(dropna=False)
        .rename_axis("decision")
        .reset_index(name="count")
    )

,source_entity,source_attribute,target_table,target_column,semantic_score,mde_status,decision
0,patient,patient_id,NaN,NaN,0.00,None,REJECT
1,patient,name,NaN,NaN,0.00,None,REJECT
2,patient,gender,NaN,NaN,0.00,None,REJECT
3,patient,dob,NaN,NaN,0.00,None,REJECT
4,patient,deceased,NaN,NaN,0.00,None,REJECT
5,patient,allergies,NaN,NaN,0.00,None,REJECT
6,patient,caregiver,NaN,NaN,0.00,None,REJECT
7,caregivers,cgid,CAREGIVERS,NaN,0.00,None,REJECT
8,caregivers,label,CAREGIVERS,NaN,0.00,None,REJECT
9,caregivers,description,CAREGIVERS,NaN,0.00,None,REJECT
10,contact,phone,NaN,NaN,0.00,None,REJECT
11,contact,address->address,NaN,NaN,0.00,None,REJECT
12,address,line1,NaN,NaN,0.00,None,REJECT
13,address,city,NaN,NaN,0.00,None,REJECT
14,address,country,NaN,NaN,0.00,None,REJECT
15,admission,admission_id,ADMISSIONS,NaN,0.00,None,REJECT
16,admission,admission_type,ADMISSIONS,NaN,0.00,None,REJECT
17,admission,admit_time,ADMISSIONS,NaN,0.00,None,REJECT
18,admission,discharge_time,ADMISSIONS,NaN,0.00,None,REJECT
19,admission,telemedicine_flag,ADMISSIONS,NaN,0.00,None,REJECT
20,admission,visit_mode,ADMISSIONS,NaN,0.00,None,REJECT
21,admission,prescriptions->prescription,ADMISSIONS,NaN,0.00,None,REJECT
22,admission,imaging->imaging,ADMISSIONS,NaN,0.00,None,REJECT
23,prescription,drug,prescriptions,NaN,0.00,None,REJECT
24,prescription,dose,prescriptions,NaN,0.00,None,REJECT
25,prescription,route,prescriptions,prescriptions.route,0.98,None,EVOLVE
26,prescription,frequency,prescriptions,NaN,0.00,None,REJECT
27,imaging,modality,NaN,NaN,0.00,None,REJECT
28,imaging,body_site,NaN,NaN,0.00,None,REJECT
29,imaging,ai_annotations->aiannotation,NaN,NaN,0.00,None,REJECT
30,aiannotation,label,NaN,NaN,0.00,None,REJECT
31,aiannotation,confidence,NaN,NaN,0.00,None,REJECT

Decision counts:

  decision  count
0   REJECT     31
1   EVOLVE      1

## 14. Evolution plan and generated SQL

In [ ]:
if evolution_df.empty:
    print("No EVOLVE operations were produced.")
else:
    display(evolution_df)

sql_statements = []
if schema_changes:
    try:
        sql_statements = migration_builder.build_migration(schema_changes)
    except Exception as exc:
        print("[WARNING] MigrationBuilder failed:", exc)

print(f"Generated SQL statements: {len(sql_statements)}")
for i, sql in enumerate(sql_statements, 1):
    print(f"{i:02d}. {sql}")

,source_entity,source_attribute,change_type,target_table,target_column,data_type
0,prescription,route,add_column,prescription,route,VARCHAR(255)

Generated SQL statements: 1
01. ALTER TABLE prescription ADD COLUMN route VARCHAR(255);

## 15. Optional DiffEngine comparison

This is a **secondary diagnostic**, not the main decision pipeline.

It allows comparison between the older structural diff route and the new semantic-decision/evolution route.

In [ ]:
diff_changes = []
try:
    diff_engine = DiffEngine(
        NamingConvention(),
        rag_matcher=matcher,
    )
    diff_changes = diff_engine.compute_diff(
        uschema,
        current_schema,
    )
    print(f"DiffEngine changes: {len(diff_changes)}")
except Exception as exc:
    print("[INFO] DiffEngine comparison unavailable:", exc)

if diff_changes:
    diff_rows = []
    for change in diff_changes:
        diff_rows.append({
            "change_type": getattr(change.change_type, "value", str(change.change_type)),
            "target_table": getattr(change, "target_table", None),
            "target_column": getattr(change, "target_column", None),
        })
    display(pd.DataFrame(diff_rows))

[RAGSchemaMatcher] LLM validation failed: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-3.6-flash\nPlease retry in 57.358737148s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.6-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '57s'}]}}

DiffEngine changes: 13

     change_type   target_table                target_column
0     add_column       patients                   patient_id
1     add_column       patients                     deceased
2     add_column       patients                    allergies
3     add_column       patients                    caregiver
4   create_table       contacts                          NaN
5   create_table        address                          NaN
6     add_column     admissions                 admission_id
7     add_column     admissions               discharge_time
8     add_column     admissions  prescriptions->prescription
9     add_column     admissions             imaging->imaging
10    add_column  prescriptions                    frequency
11  create_table       imagings                          NaN
12  create_table  aiannotations                          NaN

## 16. Quantitative evaluation when gold labels are available

The real open-world run does not invent labels.

If the OMAP/MIMIC gold dataset is available in the repository, point `GOLD_FILE` to it and use the following evaluation cell. Otherwise this section reports only retrieval/decision distributions.

Expected retrieval metrics for a labeled matching benchmark include Hit@K and MRR.

In [ ]:
GOLD_FILE = None  # Set to the real labeled OMAP/MIMIC file when available.

def normalize_name(value):
    return str(value).strip().lower()

def evaluate_hit_at_k(predictions, gold_pairs, k):
    if not predictions:
        return 0.0

    hits = 0
    for item in predictions:
        source = normalize_name(item["source"])
        candidates = [
            normalize_name(x) for x in item["candidates"][:k]
        ]
        gold = normalize_name(gold_pairs.get(source, ""))
        if gold and gold in candidates:
            hits += 1

    return hits / len(predictions)

if GOLD_FILE is not None and Path(GOLD_FILE).exists():
    print("Gold evaluation file:", GOLD_FILE)
    # Expected adapter format:
    # source -> gold target
    # Adapt this loader to the exact project dataset schema.
    with open(GOLD_FILE, "r", encoding="utf-8") as f:
        gold_data = json.load(f)

    print("Loaded gold data entries:", len(gold_data))
else:
    print(
        "No gold file configured. "
        "Do not infer scientific accuracy from the unlabeled open-world run."
    )

No gold file configured. Do not infer scientific accuracy from the unlabeled open-world run.

## 17. Safety check before SQL execution

In [ ]:
if not EXECUTE_SQL:
    print("SAFE MODE: SQL was generated but will NOT be executed.")
else:
    raise RuntimeError(
        "SQL execution is intentionally not implemented in this notebook. "
        "Review and execute migrations explicitly outside the experiment."
    )

SAFE MODE: SQL was generated but will NOT be executed.

## 18. Save reproducible artifacts

In [ ]:
def records_from_df(df):
    if df is None or df.empty:
        return []
    return json.loads(df.to_json(orient="records", force_ascii=False))

artifacts = {
    "config": {
        "database": DATABASE_URL.split("@")[-1],
        "dialect": DIALECT,
        "index_type": INDEX_TYPE,
        "top_k": TOP_K,
        "table_threshold": TABLE_THRESHOLD,
        "column_threshold": COLUMN_THRESHOLD,
        "tau_match": TAU_MATCH,
        "tau_review": TAU_REVIEW,
        "execute_sql": EXECUTE_SQL,
    },
    "u_schema": records_from_df(uschema_df),
    "target_schema": records_from_df(schema_df),
    "table_matches": records_from_df(table_df),
    "attribute_matches": records_from_df(attribute_df),
    "mde_validations": records_from_df(mde_df),
    "decisions": records_from_df(decision_df),
    "evolution": records_from_df(evolution_df),
    "sql": sql_statements,
}

artifact_file = ARTIFACT_DIR / "real_experiment_report.json"
with open(artifact_file, "w", encoding="utf-8") as f:
    json.dump(artifacts, f, ensure_ascii=False, indent=2)

table_df.to_csv(ARTIFACT_DIR / "table_matches.csv", index=False)
attribute_df.to_csv(ARTIFACT_DIR / "attribute_matches.csv", index=False)
decision_df.to_csv(ARTIFACT_DIR / "decisions.csv", index=False)

if not mde_df.empty:
    mde_df.to_csv(ARTIFACT_DIR / "mde_validations.csv", index=False)

if not evolution_df.empty:
    evolution_df.to_csv(ARTIFACT_DIR / "evolution.csv", index=False)

with open(ARTIFACT_DIR / "sql_migrations.sql", "w", encoding="utf-8") as f:
    for sql in sql_statements:
        f.write(sql.rstrip() + "\n")

print("Artifacts saved to:", ARTIFACT_DIR)

Artifacts saved to: d:\memoire\rag\1.0.0\artifacts\notebook_real_experiment

## 19. Final experiment summary

In [ ]:
summary = {
    "source_entities": len(uschema.entities),
    "source_attributes": len(uschema_rows),
    "target_tables": len(current_schema.tables),
    "indexed_kb_documents": len(kb_docs),
    "table_matches": len(table_df),
    "attribute_matches": len(attribute_df),
    "mde_validations": len(mde_df),
    "evolution_operations": len(evolution_df),
    "sql_statements": len(sql_statements),
}

if not decision_df.empty:
    summary["decision_counts"] = (
        decision_df["decision"]
        .value_counts()
        .to_dict()
    )

display(pd.DataFrame([summary]))
print("\nExperiment completed in REAL-DATA / DRY-RUN mode.")

,source_entities,source_attributes,target_tables,indexed_kb_documents,table_matches,attribute_matches,mde_validations,evolution_operations,sql_statements,decision_counts
0,8,32,72,1282,8,32,0,1,1,"{'REJECT': 31, 'EVOLVE': 1}"

Experiment completed in REAL-DATA / DRY-RUN mode.

## 20. Interpretation guide

The experiment should be interpreted in three layers:

### A. RAG quality
Use the labeled OMAP/MIMIC benchmark, when configured, for Hit@K/MRR and related metrics.

### B. Decision quality
Inspect the distribution and cases of `MATCH`, `EVOLVE`, `REVIEW`, and `REJECT`, together with semantic and MDE evidence.

### C. Evolution quality
Inspect generated `SchemaChange` objects and SQL. Do not claim evolution accuracy without an explicit gold evolution set.

**Important:** an unlabeled real database run demonstrates end-to-end integration and behavior; it does not by itself establish retrieval accuracy or evolution accuracy.